name:  Metadata Rotator

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'वीडियो का डायरेक्ट लिंक डालें (URL)'
        required: true
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          echo "Downloading video from provided URL..."
          curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -o input_video.mp4 "${{ github.event.inputs.video_url }}"

      - name: Rotate Metadata by 90 Degrees
        run: |
          echo "Applying 90 degree metadata rotation..."
          ffmpeg -i input_video.mp4 -c copy -metadata:s:v:0 rotate=90 output_video.mp4

      - name: Verify Rotation Metadata
        run: |
          echo "Checking if rotation metadata is applied..."
          ffprobe -v quiet -select_streams v:0 -show_entries stream_tags=rotate -of default=nw=1:nk=1 output_video.mp4
          

      - name: Upload Final Video
        uses: actions/upload-artifact@v4
        with:
          name: Rotated-Video
          path: output_video.mp4
          retention-days: 1
